version: '3'

services:
  backend:
    build:
      context: backend/
    ports:
      - "8000:8000"
    networks:
      - clima
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: frontend/
    ports:
      - "8501:8501"
    networks:
      - clima
    volumes:
      - ./frontend:/app

networks:
  clima: